### PR TITLE
updated crunchy container references to latest versions

### PR DESCRIPTION
**Pull request by jmccormick2001**
Steve,

I updated the crunchy specific things to reference the new container images, also some
other minor updates of directory names.

### CODE REVIEW

**Comment by thesteve0** [comment]
I don't understand the run.sh piece - can you explain before I merge

**Comment by jmccormick2001** [comment]
yep, to avoid hardcoding the image tag name in various places, I use an environment variable set up outside the template, called CCP_IMAGE_TAG.  You set this to a value like 'centos7-9.5-1.2.2' and it will add that to the image string and pull down the particular image from dockerhub.  To pass that variable into various 'oc' commands, you have to add a flag, in the case of 'oc new-app', that flag is '-p'.  In the case of 'oc process', the flag is '-v'.

So, in your workshop example of 'oc new-app' to create the database, I added '-p CCP_IMAGE_TAG=xxx' into the example/docs to include the new parameter.  The JSON template
looks for that variable now, so if you don't set it, it will not process.

The prometheus/grafana stuff is now relocated into a subdir called 'metrics' instead of 'scope'.  There is a 'run.sh' script in that directory that starts all 3 of the metrics related containers.  That run.sh script just executes the 3 'oc process' commands for you instead of manually running the 3 commands. Running these scripts requires you set up environment variables:  BUILDBASE which is the location into which you performed the 'git clone' of the examples, and CCP_IMAGE_TAG which is specified to pull a particular docker image.  The current version of CCP_IMAGE_TAG is 'cento7-9.5-1.2.2'.  You could run the 'oc process' commands directly if that would be useful to show the
workshop attendees.

lastly, the URL of the prometheus service has changed from http://crunchy-scope:9090 to
http://crunchy-prometheus:9090

**Comment by thesteve0** [comment]
Wait do I need to set it on their laptops or can I just set it with the -p?

**Comment by jmccormick2001** [comment]
if they are running the 'oc new-app' command, they just need to know to add the '-p' flag

**Comment by thesteve0** [comment]
Ok - do all the instructions now say that? And which value should they use
for the -p flag - did you include that in your merge request?

**Comment by jmccormick2001** [comment]
yep, I included it in the docs, the current value is CCP_IMAGE_TAG=centos7-9.5-1.2.2, I'll run through the examples one more time to make sure they work as well.

**Comment by thesteve0** [comment]
I just uploaded a PDF - give me 5 minutes to upload a new one with your
changes merged in so you can see how it works (or are you just using the
asciidoc?)

**Comment by jmccormick2001** [comment]
just using the asciidoc, so far it seems to work

**Comment by jmccormick2001** [comment]
I also updated the section related to starting the Prometheus server, that seems to work on my system as well...I've only tested it on Linux however.

**Comment by thesteve0** [comment]
Did you try it with the Vagrant box that I am using? That is the only thing
that matters. If that works on Linux then I should be ok but I am concerned
if this will only work on Linux laptops. Most of my class will be on
windows - we can't have shell scripts.

**Comment by jmccormick2001** [comment]
do they run the metrics containers in your class?

**Comment by thesteve0** [comment]
Nope - we ran out of time last time and I won't have time this time either.
We will need to do it for PostgresOpen though

**Comment by jmccormick2001** [comment]
cool, where is your latest vagrant file you will be using? and I'll try to test this out today.

**Comment by thesteve0** [comment]
vagrant init thesteve0/uberconf-openshift-origin

vagrant up --provider=virtualbox

Have to have the PDF produced by later tonight.

**Comment by jmccormick2001** [comment]
I tested the VM,vagrant, and the new database stuff...it all seems to work, even the old
container image still works...some things you have to do however:  to use the centos7-9.5-1.2.2 image version, I first had to do a 'docker pull crunchydata/crunchy-postgres:centos7-9.5-1.2.2' and 'docker pull crunchydata/crunchy-collect:centos7-9.5-1.2.2' to pull down the images into the VM....  if you want to use the prior 1.2.1 version that is already downloaded to that VM, all you have to do is use CCP_IMAGE_TAG=1.2.1 and that will also work.  Let me know if you need anything or find any issues, but seems to work.

**Comment by jmccormick2001** [comment]
I tried to test the web app, but it seems to hang trying to download the following
image:  Image "registry.access.redhat.com/rhscl/python-35-rhel7:latest" not available locally, pulling ..

I notice on the VM that the centos version of pythong 3.5 is already pulled down, so I'm not sure how to change the web app to use that version of python instead of the rhscl version..

**Comment by thesteve0** [comment]
Yeah I am not sure either just yet. Can you please put in a pull request to
change the doc to use the 1.2.1 versions since I already have those cached.
Was there some huge change or critical bug fix in 1.2.2?

Thanks for all your help!

**Comment by jmccormick2001** [comment]
tons of new changes but not much you actually see as a user, some changes were made to support the container running on Redhat Dedicated but thats not what your demo is all about so no real need for you to upgrade yet.  I'll enter the PR to use the 1.2.1 version.

**Comment by thesteve0** [comment]
Thanks!

**Pull request merged**
